# Site settings
title: Easter Blog
SEOTitle: 樊东方的博客 | Easter
header-img: img/config/home-bg.jpg
email: shenbaoone@gmail.com
description: " | 这里是樊东方的个人博客，与你一起发现更大的世界。樊东方少抱怨，多思考，未来更美好！！！"

keyword: "shenbaoone@gmail.com, 沈宝, ShenBao,小宝,XiaoBao，知秋，@沈宝,@小宝,@ShenBao,@XiaoBao,@知秋，沈宝的博客,秋思浪人,QiusiLangren，秋思浪人的博客,ShenBao Blog,知秋的博客， 博客, 个人网站, 互联网, 前端，web developer,JavaScript,Js,ES5,ES6,React,Redux,React Native,SVN,Git,Gulp,WebPack,Fis3."

url: "https://shenbao.github.io"              # your host, for absolute URL
createTime: '2015'

baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'
# 导航栏
categories_path: categories
tags_path: tags
about_path: about


# SNS settings
RSS: false
weibo_username:  ShenBaoPro
zhihu_username:  shenbao
github_username: ShenBao
# twitter_username:  
# facebook_username:  
# linkedin_username:  firstname-lastname-idxxxx



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 8
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: no # true                          # if you want to customize anchor. check out line:181 of `post.html`  文章中标题前面的 # 符号
# timezone: CN                                # 时间设置


# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
input: GFM                            # use Github Flavored Markdown !important



# Disqus settings
disqus_username: ShenBao

# Hypercomments settings
hypercomments_userid: 91931

# Duoshuo settings
# duoshuo_username: shenbao
# Share component is depend on Comment so we can NOT use share only.
# duoshuo_share: true                     # set to false if you want to use Comment without Sharing




# Analytics settings
# Baidu Analytics 
# ba_track_id: [your track id]

# Google Analytics
# ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
# ga_domain: shenbao.github.io



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.#添加侧边栏
sidebar-about-description: "动次达次，<br>动次达次！！" # 简单的描述一下你自己
sidebar-avatar: /img/config/my-head.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`你的大头贴，请使用绝对地址



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 0              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true


# Friends
# friends: [
#     {
#         title: "原博客",
#         href: "https://shenbao.github.io/blog"
#     },
#     {
#         title: "React技术栈",
#         href: "https://shenbao.github.io/ishehui"
#     }
# ]

# Extends
extends: [
     {
        title: "Blog",
        href: "https://shenbao.github.io"
    },
    {
        title: "开发笔记",
        href: "https://shenbao.github.io/shenbao-notes"
    },
    {
        title: "diary",
        href: "https://shenbao.github.io/shenbao-diary"
    },
    {
        title: "API doc",
        href: "https://shenbao.github.io/blog"
    },
    {
        title: "ISHFE",
        href: "https://shenbao.github.io/ishehui"
    }
]
